
ARCHOBJS += \
$(ARCH_SRCDIR)/mem/mm.c.o    \
$(ARCH_SRCDIR)/mem/stack_trace.c.o    \
$(ARCH_SRCDIR)/mem/pdpt.c.o    \
$(ARCH_SRCDIR)/mem/pd.c.o    \
$(ARCH_SRCDIR)/mem/pt.c.o    \
$(ARCH_SRCDIR)/mem/pagefault.c.o    \
