
ARCH_SRC += \
$(ARCH_SRCDIR)/mem/mm.c    \
$(ARCH_SRCDIR)/mem/stack_trace.c    \
$(ARCH_SRCDIR)/mem/pdpt.c    \
$(ARCH_SRCDIR)/mem/pd.c    \
$(ARCH_SRCDIR)/mem/pt.c    \
$(ARCH_SRCDIR)/mem/pagefault.c    \
