
ARCH_SRC += \
$(ARCH_SRCDIR)/mem/mm.c    \
$(ARCH_SRCDIR)/mem/stack_trace.c    \
$(ARCH_SRCDIR)/mem/pagedir_ptrtable.c    \
$(ARCH_SRCDIR)/mem/pagedir.c    \
$(ARCH_SRCDIR)/mem/pagetable.c    \
$(ARCH_SRCDIR)/mem/pagefault.c    \
