
KERNEL_SRC += \
$(KERNEL_SRCDIR)/string/memcmp.c \
$(KERNEL_SRCDIR)/string/strcat.c \
$(KERNEL_SRCDIR)/string/strcpy.c \
$(KERNEL_SRCDIR)/string/strlen.c \
$(KERNEL_SRCDIR)/string/memset.c \
$(KERNEL_SRCDIR)/string/strncat.c \
$(KERNEL_SRCDIR)/string/memcpy.c \
$(KERNEL_SRCDIR)/string/strcmp.c \
