
OBJS_KERNEL += \
kernel/string/memcmp.o \
kernel/string/strcat.o \
kernel/string/strcpy.o \
kernel/string/strlen.o \
kernel/string/memset.o \
kernel/string/strncat.o \
kernel/string/memcpy.o \
kernel/string/strcmp.o \
