
KERNEL_SRC += \
kernel/string/memcmp.c \
kernel/string/strcat.c \
kernel/string/strcpy.c \
kernel/string/strlen.c \
kernel/string/memset.c \
kernel/string/strncat.c \
kernel/string/memcpy.c \
kernel/string/strcmp.c \
