
#ifndef _DXGMX_BITS_X86_CLOCKSOURCES_H
#define _DXGMX_BITS_X86_CLOCKSOURCES_H

typedef enum
E_ClockSources
{
    CLOCKSOURCE_RTC,
    CLOCKSOURCE_ENUM_END
} ClockSources;

#endif //!_DXGMX_BITS_X86_CLOCKSOURCES_H
