
WD := dxgmx

HEADERS += \
$(WD)/abandon_ship.h \
$(WD)/kstdio.h \
$(WD)/kctype.h \
$(WD)/kerrno.h \
$(WD)/kstdlib.h \
$(WD)/kstring.h \

include $(INCLUDE_DIR)/dxgmx/x86/Makefile
include $(INCLUDE_DIR)/dxgmx/video/Makefile
include $(INCLUDE_DIR)/dxgmx/gcc/Makefile
