
HEADERS += \
$(INCLUDEDIR)/dxgmx/abandon_ship.h \
$(INCLUDEDIR)/dxgmx/assert.h \
$(INCLUDEDIR)/dxgmx/attrs.h \
$(INCLUDEDIR)/dxgmx/bitwise.h \
$(INCLUDEDIR)/dxgmx/timer.h \
$(INCLUDEDIR)/dxgmx/cpu.h \
$(INCLUDEDIR)/dxgmx/ctype.h \
$(INCLUDEDIR)/dxgmx/errno.h \
$(INCLUDEDIR)/dxgmx/kabort.h \
$(INCLUDEDIR)/dxgmx/kdefs.h \
$(INCLUDEDIR)/dxgmx/klog.h \
$(INCLUDEDIR)/dxgmx/kprintf.h \
$(INCLUDEDIR)/dxgmx/kstack.h \
$(INCLUDEDIR)/dxgmx/math.h \
$(INCLUDEDIR)/dxgmx/stdlib.h \
$(INCLUDEDIR)/dxgmx/string.h \
$(INCLUDEDIR)/dxgmx/time.h \
$(INCLUDEDIR)/dxgmx/todo.h \
$(INCLUDEDIR)/dxgmx/types.h \
$(INCLUDEDIR)/dxgmx/stdio.h \
$(INCLUDEDIR)/dxgmx/compiler_attrs.h \

include $(INCLUDEDIR)/dxgmx/bits/Makefile
include $(INCLUDEDIR)/dxgmx/mem/Makefile
include $(INCLUDEDIR)/dxgmx/video/Makefile
include $(INCLUDEDIR)/dxgmx/$(SRCARCH)/Makefile
include $(INCLUDEDIR)/dxgmx/utils/Makefile
include $(INCLUDEDIR)/dxgmx/crypto/Makefile
