
#ifndef _DXGMX_SYSCALL_NUMBERS_H
#define _DXGMX_SYSCALL_NUMBERS_H

#define SYSCALL_EXIT 1
#define SYSCALL_OPEN 2
#define SYSCALL_READ 3
#define SYSCALL_EXECVE 4

#define SYSCALL_DXGMX_LOG 0xb008

#endif // !_DXGMX_SYSCALL_NUMBERS_H
