
HEADERS += \
$(INCLUDEDIR)/dxgmx/x86/acpi.h \
$(INCLUDEDIR)/dxgmx/x86/cmos.h \
$(INCLUDEDIR)/dxgmx/x86/cpuid.h \
$(INCLUDEDIR)/dxgmx/x86/gdt.h \
$(INCLUDEDIR)/dxgmx/x86/idt.h \
$(INCLUDEDIR)/dxgmx/x86/interrupt_frame.h \
$(INCLUDEDIR)/dxgmx/x86/interrupts.h \
$(INCLUDEDIR)/dxgmx/x86/pic.h \
$(INCLUDEDIR)/dxgmx/x86/portio.h \
$(INCLUDEDIR)/dxgmx/x86/rtc.h \
$(INCLUDEDIR)/dxgmx/x86/tsc.h \
$(INCLUDEDIR)/dxgmx/x86/vga_text.h \
$(INCLUDEDIR)/dxgmx/x86/pit.h \

ifeq ($(CONFIG_BOOTSPEC),multiboot)
	HEADERS += $(INCLUDEDIR)/dxgmx/x86/multiboot.h 
endif
