
HEADERS += \
$(INCLUDE_SRCDIR)/dxgmx/x86/acpi.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/cmos.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/cpuid.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/gdt.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/idt.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/interrupt_frame.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/interrupts.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/pic.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/portio.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/rtc.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/tsc.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/vga_text.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/pit.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/pagedir.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/pagetable.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/pagedir_ptrtable.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/exceptions.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/pci.h \
$(INCLUDE_SRCDIR)/dxgmx/x86/serial.h \

ifeq ($(CONFIG_BOOTSPEC),multiboot)
	HEADERS += $(INCLUDE_SRCDIR)/dxgmx/x86/multiboot.h 
endif
