
KERNEL_SRC += \
$(KERNEL_SRCDIR)/kstdlib/ctype.c \
$(KERNEL_SRCDIR)/kstdlib/math.c \
$(KERNEL_SRCDIR)/kstdlib/stdio.c \
$(KERNEL_SRCDIR)/kstdlib/stdlib.c \
$(KERNEL_SRCDIR)/kstdlib/string.c \
$(KERNEL_SRCDIR)/kstdlib/time.c \
