
OBJS_ARCH += \
arch/x86/init_stage1.o \
arch/x86/init_stage2.o \
arch/x86/cpu.o \
arch/x86/cpuid.o \

include $(ARCH_DIR)/boot/Makefile
include $(ARCH_DIR)/video/Makefile
include $(ARCH_DIR)/int/Makefile
include $(ARCH_DIR)/mem/Makefile
include $(ARCH_DIR)/gdt/Makefile
