
KERNELOBJS += \
$(KERNEL_SRCDIR)/kprintf.c.o \
$(KERNEL_SRCDIR)/kabort.c.o \
$(KERNEL_SRCDIR)/klog.c.o \
$(KERNEL_SRCDIR)/kinit_stage2.c.o \
$(KERNEL_SRCDIR)/ksyms.c.o \
$(KERNEL_SRCDIR)/kimg.c.o \
$(KERNEL_SRCDIR)/module.c.o \
$(KERNEL_SRCDIR)/panic.c.o \
$(KERNEL_SRCDIR)/user.c.o \
$(KERNEL_SRCDIR)/kstdio.c.o \
$(KERNEL_SRCDIR)/kboot.c.o \

include $(KERNEL_SRCDIR)/mem/Makefile
include $(KERNEL_SRCDIR)/utils/Makefile
include $(KERNEL_SRCDIR)/crypto/Makefile
include $(KERNEL_SRCDIR)/kstdlib/Makefile
include $(KERNEL_SRCDIR)/storage/Makefile
include $(KERNEL_SRCDIR)/fs/Makefile
include $(KERNEL_SRCDIR)/elf/Makefile
include $(KERNEL_SRCDIR)/proc/Makefile
include $(KERNEL_SRCDIR)/syscalls/Makefile
include $(KERNEL_SRCDIR)/sched/Makefile
include $(KERNEL_SRCDIR)/time/Makefile
