
OBJS_KERNEL += \
kernel/abandon_ship.o \
kernel/mmap.o \

include $(KERNEL_DIR)/ctype/Makefile
include $(KERNEL_DIR)/errno/Makefile
include $(KERNEL_DIR)/stdio/Makefile
include $(KERNEL_DIR)/stdlib/Makefile
include $(KERNEL_DIR)/string/Makefile
