
OBJS_KERNEL += \
kernel/stdlib/abs.o \
kernel/stdlib/labs.o \
kernel/stdlib/llabs.o \
kernel/stdlib/itoa.o \
kernel/stdlib/strtol.o \
kernel/stdlib/ltoa.o \
kernel/stdlib/ultoa.o \
kernel/stdlib/ulltoa.o \
kernel/stdlib/utoa.o \
kernel/stdlib/lltoa.o \
