
KERNEL_SRC += \
$(KERNEL_SRCDIR)/stdlib/abs.c \
$(KERNEL_SRCDIR)/stdlib/labs.c \
$(KERNEL_SRCDIR)/stdlib/llabs.c \
$(KERNEL_SRCDIR)/stdlib/itoa.c \
$(KERNEL_SRCDIR)/stdlib/strtol.c \
$(KERNEL_SRCDIR)/stdlib/ltoa.c \
$(KERNEL_SRCDIR)/stdlib/ultoa.c \
$(KERNEL_SRCDIR)/stdlib/ulltoa.c \
$(KERNEL_SRCDIR)/stdlib/utoa.c \
$(KERNEL_SRCDIR)/stdlib/lltoa.c \
