
KERNEL_SRC += \
kernel/stdlib/abs.c \
kernel/stdlib/labs.c \
kernel/stdlib/llabs.c \
kernel/stdlib/itoa.c \
kernel/stdlib/strtol.c \
kernel/stdlib/ltoa.c \
kernel/stdlib/ultoa.c \
kernel/stdlib/ulltoa.c \
kernel/stdlib/utoa.c \
kernel/stdlib/lltoa.c \
