
KERNEL_SRC += \
kernel/time/timespec_add.c \
kernel/time/asctime.c \
kernel/time/clock.c \
kernel/time/ctime.c \
kernel/time/difftime.c \
kernel/time/gmtime.c \
kernel/time/localtime.c \
kernel/time/mktime.c \
kernel/time/strftime.c \
kernel/time/time.c \
