
KERNEL_SRC += \
$(KERNEL_SRCDIR)/time/asctime.c \
$(KERNEL_SRCDIR)/time/clock.c \
$(KERNEL_SRCDIR)/time/ctime.c \
$(KERNEL_SRCDIR)/time/difftime.c \
$(KERNEL_SRCDIR)/time/gmtime.c \
$(KERNEL_SRCDIR)/time/localtime.c \
$(KERNEL_SRCDIR)/time/mktime.c \
$(KERNEL_SRCDIR)/time/strftime.c \
$(KERNEL_SRCDIR)/time/time.c \
