#!/bin/bash

help() {
	echo "unmount-root.sh [options]"
	echo
	echo "Mount the kernel's sysroot on the host machine."
	echo 
	echo "options:"
	echo "  -h, --help         Print this message and exit."
	echo "  --cachefile        Path to cache file generated by mount-root.sh."
}

while [[ $# -gt 0 ]]
do
	key="$1"
	case "$key" in
		"--cachefile")
			CACHEFILE="$2"
			shift 2
		;;
		"-h"|"--help")
			help
			exit 1
		;;
		*)
			shift
		;;
	esac
done

if [ -z "$CACHEFILE" ]; then
	help
	echo 
	echo "Bad usage"
	exit 1
fi

LOOPDEV=$(cat $CACHEFILE)

MNTPOINT=$(findmnt -o TARGET -n ${LOOPDEV}p1)

umount ${LOOPDEV}p1
losetup --detach $LOOPDEV

rmdir $MNTPOINT
rm $CACHEFILE

echo Unmounted and detached $LOOPDEV
