
KERNEL_SRC += \
$(KERNEL_SRCDIR)/syscalls/syscalls.c \
$(KERNEL_SRCDIR)/syscalls/syscall_exit.c \
$(KERNEL_SRCDIR)/syscalls/syscall_read.c \
$(KERNEL_SRCDIR)/syscalls/syscall_execve.c \
$(KERNEL_SRCDIR)/syscalls/syscall_debug.c \
