
HEADERS += \
$(INCLUDEDIR)/dxgmx/mem/mmap.h \
$(INCLUDEDIR)/dxgmx/mem/pagedir.h \
$(INCLUDEDIR)/dxgmx/mem/pgframe_alloc.h \
$(INCLUDEDIR)/dxgmx/mem/pagesize.h \
$(INCLUDEDIR)/dxgmx/mem/pagetable.h \
$(INCLUDEDIR)/dxgmx/mem/paging.h \
