
HEADERS += \
$(INCLUDEDIR)/dxgmx/mem/mmap.h \
$(INCLUDEDIR)/dxgmx/mem/pgframe_alloc.h \
$(INCLUDEDIR)/dxgmx/mem/pagesize.h \
$(INCLUDEDIR)/dxgmx/mem/paging.h \
$(INCLUDEDIR)/dxgmx/mem/memrange.h \
$(INCLUDEDIR)/dxgmx/mem/mmanager.h \
