
HEADERS += \
$(INCLUDEDIR)/dxgmx/mem/kpaging.h \
$(INCLUDEDIR)/dxgmx/mem/mmap.h \
$(INCLUDEDIR)/dxgmx/mem/pagedir.h \
$(INCLUDEDIR)/dxgmx/mem/pageframe.h \
$(INCLUDEDIR)/dxgmx/mem/pagesize.h \
$(INCLUDEDIR)/dxgmx/mem/pagetable.h \
$(INCLUDEDIR)/dxgmx/mem/paging.h \
