
OBJS_LIBKC += \

include $(LIBKC_DIR)/ctype/Makefile
include $(LIBKC_DIR)/errno/Makefile
include $(LIBKC_DIR)/stdio/Makefile
include $(LIBKC_DIR)/stdlib/Makefile
include $(LIBKC_DIR)/string/Makefile
